package com.mycompany.controlestudio.vista;

import com.mycompany.controlestudio.modelo.persona;
import javax.swing.JOptionPane;


public class DashboardFrame extends javax.swing.JFrame {
    
    private persona personaLogueada ;
 
    public DashboardFrame() {
        initComponents();
        this.personaLogueada = persona;
        configurarDashboardSegunRol();
        cargarDatosResumen();
        this.setLocationRelativeTo(null);
        this.setTitle("Control de Estudios - Dashboard (" + persona.getNombre_usuario() + ")");
        
        private void configurarDashboardSegunRol() {
        lblBienvenida.setText("Bienvenido, " + personaLogueada.getNombre_usuario() +
                " (Rol: " + personaLogueada.getTipo_rol() + ")");

        switch (personaLogueada.getTipo_rol()) {
            case Administrador:
                menuGestion.setVisible(true);
                btnAdminUsuarios.setVisible(true);
                break;
            case Profesor:
                menuGestion.setVisible(false);
                btnAdminUsuarios.setVisible(false);
                lblMaterias.setText("Materias asignadas: " + ProfesorService.obtenerMateriasPorProfesor(personaLogueada.getId_persona()));
                break;
            case Estudiante:
                menuGestion.setVisible(false);
                btnAdminUsuarios.setVisible(false);
                lblMaterias.setText("Materias inscritas: " + estudianteService.obtenerMateriasPorEstudiante(personaLogueada.getId_persona()));
                lblNotas.setText("Promedio general: " + estudianteService.obtenerPromedioPorEstudiante(personaLogueada.getId_persona()));
                break;
        }
    }

    private void cargarDatosResumen() {
        lblMaterias.setText("Cargando...");
        lblNotas.setText("Cargando...");

        if (personaLogueada.getTipo_rol() == persona.TipoRol.Profesor) {
            lblMaterias.setText("Materias asignadas: " + profesorService.obtenerMateriasPorProfesor(personaLogueada.getId_persona()));
        } else if (personaLogueada.getTipo_rol() == persona.TipoRol.Estudiante) {
            lblMaterias.setText("Materias inscritas: " + estudianteService.obtenerMateriasPorEstudiante(personaLogueada.getId_persona()));
            lblNotas.setText("Promedio general: " + estudianteService.obtenerPromedioPorEstudiante(personaLogueada.getId_persona()));
            
        }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBienvenidaUsuarioText = new javax.swing.JLabel();
        jBtnGestionarUsuarios = new javax.swing.JButton();
        jBtnGestionarEspecialidades = new javax.swing.JButton();
        jBtnGestionarMaterias = new javax.swing.JButton();
        JBarraDeMenu = new javax.swing.JMenuBar();
        JMenuArchivo = new javax.swing.JMenu();
        JmenuItemCerrarSesion = new javax.swing.JMenuItem();
        JmenuItemSalir = new javax.swing.JMenuItem();
        JmenuItemGestion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuGestionEspecialidades = new javax.swing.JMenuItem();
        jMenuGestionMaterias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBienvenidaUsuarioText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBienvenidaUsuarioText.setForeground(new java.awt.Color(0, 51, 255));
        jLabelBienvenidaUsuarioText.setText("Welcome para usuario ingresado");

        jBtnGestionarUsuarios.setBackground(new java.awt.Color(0, 51, 255));
        jBtnGestionarUsuarios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnGestionarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGestionarUsuarios.setText("Administrar Usuarios");
        jBtnGestionarUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnGestionarEspecialidades.setBackground(new java.awt.Color(0, 51, 255));
        jBtnGestionarEspecialidades.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnGestionarEspecialidades.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGestionarEspecialidades.setText("Gestionar Especialidades");
        jBtnGestionarEspecialidades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnGestionarEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGestionarEspecialidadesActionPerformed(evt);
            }
        });

        jBtnGestionarMaterias.setBackground(new java.awt.Color(0, 51, 255));
        jBtnGestionarMaterias.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnGestionarMaterias.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGestionarMaterias.setText("Gestionar Materias");
        jBtnGestionarMaterias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jBtnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnGestionarMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBienvenidaUsuarioText)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnGestionarEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelBienvenidaUsuarioText)
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGestionarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnGestionarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(jBtnGestionarEspecialidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(275, 275, 275))
        );

        JMenuArchivo.setText("Archivo");

        JmenuItemCerrarSesion.setText("Cerrar Sesión");
        JMenuArchivo.add(JmenuItemCerrarSesion);

        JmenuItemSalir.setText("Salir");
        JMenuArchivo.add(JmenuItemSalir);

        JBarraDeMenu.add(JMenuArchivo);

        JmenuItemGestion.setText("Gestión");

        jMenuItem1.setText("Gestionar Usuarios");
        JmenuItemGestion.add(jMenuItem1);

        jMenuGestionEspecialidades.setText("Gestionar Especialidades");
        JmenuItemGestion.add(jMenuGestionEspecialidades);

        jMenuGestionMaterias.setText("Gestionar Materias");
        JmenuItemGestion.add(jMenuGestionMaterias);

        JBarraDeMenu.add(JmenuItemGestion);

        setJMenuBar(JBarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGestionarEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGestionarEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGestionarEspecialidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JBarraDeMenu;
    private javax.swing.JMenu JMenuArchivo;
    private javax.swing.JMenuItem JmenuItemCerrarSesion;
    private javax.swing.JMenu JmenuItemGestion;
    private javax.swing.JMenuItem JmenuItemSalir;
    private javax.swing.JButton jBtnGestionarEspecialidades;
    private javax.swing.JButton jBtnGestionarMaterias;
    private javax.swing.JButton jBtnGestionarUsuarios;
    private javax.swing.JLabel jLabelBienvenidaUsuarioText;
    private javax.swing.JMenuItem jMenuGestionEspecialidades;
    private javax.swing.JMenuItem jMenuGestionMaterias;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
